services:
  - type: web
    name: meme-card-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    domains:
      - meme-card-game.onrender.com 